#!/usr/bin/env python3
"""Verify Dart-produced Concrete ciphertexts via Python deserialization + optional decryption.

Used by cross_language_encrypt_test.dart to verify that Dart's
lweEncryptSeeded + serializeValue produces ciphertext that Python
can deserialize (format compatibility) and, for models where input
and output specs match, decrypt to the correct plaintext integers.

Protocol:
  Request  (stdin):  {
      "client_zip_path": str,    -- path to client.zip
      "full_keys_path": str,     -- path to full_keys.bin (Keys.serialize() output)
      "ciphertext_b64": str      -- base64-encoded serialized Value (Cap'n Proto)
  }
  Response (stdout): {
      "status": "ok",
      "deserialized": true,          -- always true if we get here
      "raw_integers": [int, ...],    -- decrypted values (if specs match)
      "decrypt_skipped": bool,       -- true if input/output specs differ
      "decrypt_skip_reason": str     -- reason for skipping (if applicable)
  }
  Error    (stdout): { "error": str, "status": "error" }

The full_keys.bin file contains the complete concrete-python Keys object
serialized via Keys.serialize(). This allows restoring the exact same key
material that Dart uses (originally generated by generate_models.py).

IMPORTANT: FHEModelClient.deserialize_decrypt uses the OUTPUT circuit
specification for decryption. This only produces correct results when the
input and output specs (LWE dimension, encoding width, signedness) match.
For models where they differ, we skip decryption and only verify
deserialization succeeds (format compatibility).

Requirements: concrete-ml == 1.9.0
"""

import base64
import json
import sys
import traceback
import zipfile

import numpy as np


def _get_input_output_specs(client_zip_path):
    """Extract input and output LWE specs from client.specs.json."""
    with zipfile.ZipFile(client_zip_path) as zf:
        specs = json.loads(zf.read("client.specs.json"))

    circuits = specs.get("circuits", [])
    if not circuits:
        return None, None

    circuit = circuits[0]
    inp = circuit["inputs"][0]["typeInfo"].get("lweCiphertext", {})
    out = circuit["outputs"][0]["typeInfo"].get("lweCiphertext", {})

    return inp, out


def _specs_match_for_decrypt(inp_spec, out_spec):
    """Check if input and output specs are compatible for cross-decryption.

    Returns (match: bool, reason: str).
    """
    if not inp_spec or not out_spec:
        return False, "missing cipher specs"

    inp_enc = inp_spec.get("encryption", {})
    out_enc = out_spec.get("encryption", {})
    inp_encoding = inp_spec.get("encoding", {}).get("integer", {})
    out_encoding = out_spec.get("encoding", {}).get("integer", {})

    if inp_enc.get("lweDimension") != out_enc.get("lweDimension"):
        return False, (
            f"LWE dimension mismatch: "
            f"input={inp_enc.get('lweDimension')}, "
            f"output={out_enc.get('lweDimension')}"
        )
    if inp_enc.get("keyId") != out_enc.get("keyId"):
        return False, (
            f"key ID mismatch: input={inp_enc.get('keyId')}, "
            f"output={out_enc.get('keyId')}"
        )
    if inp_encoding.get("width") != out_encoding.get("width"):
        return False, (
            f"encoding width mismatch: "
            f"input={inp_encoding.get('width')}, "
            f"output={out_encoding.get('width')}"
        )
    if inp_encoding.get("isSigned") != out_encoding.get("isSigned"):
        return False, (
            f"signedness mismatch: "
            f"input={inp_encoding.get('isSigned')}, "
            f"output={out_encoding.get('isSigned')}"
        )
    inp_shape = inp_spec.get("concreteShape", {}).get("dimensions", [])
    out_shape = out_spec.get("concreteShape", {}).get("dimensions", [])
    if inp_shape != out_shape:
        return False, (
            f"shape mismatch: input={inp_shape}, output={out_shape}"
        )
    return True, "specs match"


def main():
    try:
        request = json.loads(sys.stdin.read())

        client_zip_path = request["client_zip_path"]
        full_keys_path = request["full_keys_path"]
        ciphertext_b64 = request["ciphertext_b64"]

        ciphertext_bytes = base64.b64decode(ciphertext_b64)

        import concrete.fhe as fhe
        from concrete.ml.deployment import FHEModelClient
        from pathlib import Path

        # Step 1: Verify deserialization (format compatibility).
        # This is the primary check -- if Dart's Cap'n Proto serialization
        # is incompatible, this will throw.
        value = fhe.Value.deserialize(ciphertext_bytes)

        # Step 2: Check if input/output specs match for decryption.
        inp_spec, out_spec = _get_input_output_specs(client_zip_path)
        specs_ok, reason = _specs_match_for_decrypt(inp_spec, out_spec)

        if not specs_ok:
            response = {
                "status": "ok",
                "deserialized": True,
                "raw_integers": [],
                "decrypt_skipped": True,
                "decrypt_skip_reason": reason,
            }
        else:
            # Step 3: Full decryption -- only when input/output specs match.
            client_zip = Path(client_zip_path)
            client_dir = client_zip.parent

            client = FHEModelClient(path_dir=str(client_dir))

            # Load the exact keys that were used by Dart.
            full_keys_bytes = Path(full_keys_path).read_bytes()
            client.client.keys.load_from_bytes(full_keys_bytes)

            # Deserialize and decrypt. Since input/output specs match,
            # process_output with position=0 uses the same encoding as
            # the input, so decryption recovers the original plaintext.
            raw_quant = client.deserialize_decrypt(ciphertext_bytes)
            raw_integers = [int(v) for v in np.array(raw_quant).flatten().tolist()]

            response = {
                "status": "ok",
                "deserialized": True,
                "raw_integers": raw_integers,
                "decrypt_skipped": False,
                "decrypt_skip_reason": "",
            }
    except Exception as e:
        response = {
            "error": f"{type(e).__name__}: {e}\n{traceback.format_exc()}",
            "status": "error",
        }

    sys.stdout.write(json.dumps(response) + "\n")
    sys.stdout.flush()


if __name__ == "__main__":
    main()
